embed_assets: on
#package_assets: always

javascripts:
  portfolio:
    - public/javascripts/jquery.js
    - public/javascripts/*.js
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.pack.js
  blog:
    - public/javascripts/jquery.js
    - public/javascripts/*.js
  post:
    - public/javascripts/jquery.js
    - public/javascripts/*.js
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/jquery.snippet.min.js
    - public/javascripts/blog/post.js

stylesheets:
  portfolio:
    - public/stylesheets/daviferreira.css
    - public/stylesheets/msgtopo.css
    - public/stylesheets/portfolio.css
    - public/javascripts/fancybox/*.css
  blog:
    - public/stylesheets/blog.css
  post:
    - public/stylesheets/msgtopo.css
    - public/stylesheets/blog.css
    - public/stylesheets/jquery.snippet.min.css
    - public/javascripts/fancybox/*.css
