embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/*.js
  portfolio:
    - public/javascripts/fancybox/jquery.easing-1.3.pack.js
    - public/javascripts/fancybox/jquery.mousewheel-3.0.4.pack.js
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.pack.js
  post:
    - public/javascripts/sh/scripts/*.js

stylesheets:
  common:
    - public/stylesheets/daviferreira.css
    - public/stylesheets/msgtopo.css
  portfolio:
    - public/stylesheets/portfolio.css
    - public/javascripts/fancybox/*.css
  blog:
    - public/stylesheets/blog.css
  post:
    - public/javascripts/sh/styles/shCore.css
    - public/javascripts/sh/styles/shThemeDefault.css

